#!/usr/bin/env python3
"""Loader + lookups for the ingested build database (data/build_data.json).

The database is generated by builds/ingest.py from the sources named in
docs/build-data-sources.md and carries its own provenance block, so a wrong number can
always be traced back to "where did this value come from?" (brief section 2).

The file lives under data/, which the public repo does not ship (data/ is gitignored
except for .gitkeep): a fresh clone runs `python builds/ingest.py` once, and every
lookup here works against the generated file. Tests build their own tiny databases.
"""
import json
import os

SCHEMA_VERSION = 1
DEFAULT_NAME = 'build_data.json'
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def default_path():
    """The generated database inside the repo's data/ directory."""
    return os.path.join(REPO_ROOT, 'data', DEFAULT_NAME)


def load(path=None, allow_missing=False):
    """Read the build database -> dict, or None when it is missing.

    A missing file is not an exception by default (the caller usually wants to tell the
    user to run the ingest): pass allow_missing=False to raise a FileNotFoundError with
    that instruction.
    """
    path = path or default_path()
    if not os.path.exists(path):
        if allow_missing:
            return None
        raise FileNotFoundError(
            'no build database at %s - run: python builds/ingest.py' % path)
    with open(path, encoding='utf-8') as fh:
        db = json.load(fh)
    if not isinstance(db, dict):
        raise ValueError('build database %s is not a JSON object' % path)
    db.setdefault('equipment', {})
    db.setdefault('mods', {})
    return db


def index(db, kind):
    """{id: row} for 'equipment' or 'mods' (already keyed by canonical id)."""
    return (db or {}).get(kind) or {}


def find_equipment(db, key, all_matches=False):
    """Equipment by canonical id, then slug, then exact name (case-insensitive)."""
    return _find(index(db, 'equipment'), key, all_matches)


def find_mod(db, key, all_matches=False):
    """Mod by canonical id, then slug, then exact name (case-insensitive).

    A name can be ambiguous: the catalog ships starter copies of some mods under one display
    name, and obsolete internal leftovers wearing a real card's name. The starter copy now
    carries the wiki's own name ("Flawed Serration"), and `_variant_rank` puts the real card
    first, then shadow copies, then the highest rank cap - pass all_matches=True for every
    candidate.
    """
    return _find(index(db, 'mods'), key, all_matches)


def find_all(db, key, kind=None):
    """Every match for a key in 'mods' / 'equipment' / both, best candidate first."""
    out = []
    for bucket in (('equipment', 'mods') if kind is None else (kind,)):
        rows, ranked = _ranked(index(db, bucket), key)
        for row in ranked:
            out.append(dict(row, bucket=bucket))
    return out


def _variant_rank(row):
    """Sort key for duplicate display names: the real card first, then a shadow copy, then rank.

    'shadowed' rows are the catalog's obsolete internal leftovers (a rank-10 "Serration" on an
    /Expert/ path the wiki does not list); a name lookup must never hand one of those back.
    """
    shadowed = 1 if row.get('shadowed') else 0
    variant = str(row.get('variant') or '')
    order = {'': 0, 'beginner': 1, 'intermediate': 2, 'expert': 3}.get(variant, 4)
    return (shadowed, order, -(row.get('max_rank') or 0))


def _ranked(rows, key):
    """(matched_rows, sorted_rows) for one bucket - the core of every lookup here."""
    if not key:
        return [], []
    if key in rows:
        return [rows[key]], [rows[key]]
    low = str(key).strip().lower()
    hits = [row for row in rows.values() if str(row.get('slug') or '').lower() == low]
    if not hits:
        hits = [row for row in rows.values() if str(row.get('name') or '').lower() == low]
    hits.sort(key=_variant_rank)
    return hits, hits


def _find(rows, key, all_matches=False):
    matches, _ = _ranked(rows, key)
    if not matches:
        return None
    return matches if all_matches else matches[0]


def search(db, query, limit=25, kind=None):
    """Substring search over names/slugs - the developer/debug surface and future UI."""
    needle = str(query or '').strip().lower()
    if not needle:
        return []
    out = []
    for bucket in (('equipment', 'mods') if kind is None else (kind,)):
        for row in index(db, bucket).values():
            hay = '%s %s' % (row.get('name') or '', row.get('slug') or '')
            if needle in hay.lower():
                out.append(dict(row, bucket=bucket))
    out.sort(key=lambda r: (len(r.get('name') or ''), r.get('name') or ''))
    return out[:limit]


def sources(db):
    """The provenance block (which source owns which kind of data)."""
    return (db or {}).get('sources') or {}


def summary(db):
    """Counts and stamps - what the debug surface prints."""
    db = db or {}
    equip = index(db, 'equipment')
    mods = index(db, 'mods')
    by_kind = {}
    for row in equip.values():
        by_kind[row.get('kind')] = by_kind.get(row.get('kind'), 0) + 1
    return {'schema_version': db.get('schema_version'),
            'generated': db.get('generated_iso'), 'equipment': len(equip),
            'equipment_by_kind': by_kind, 'mods': len(mods),
            'game_version': (db.get('game_data') or {}).get('source_version'),
            'content_hash': db.get('content_hash'),
            'notes': len(db.get('notes') or [])}


def equipment_of_kind(db, kind):
    """Every equipment row of one kind, name-sorted (for pickers)."""
    rows = [r for r in index(db, 'equipment').values() if r.get('kind') == kind]
    return sorted(rows, key=lambda r: r.get('name') or '')


def mods_for_kind(db, kind, limit=None):
    """Every mod installable on one equipment kind, name-sorted."""
    rows = []
    for row in index(db, 'mods').values():
        targets = row.get('targets') or ()
        if kind in targets:
            rows.append(row)
    rows.sort(key=lambda r: r.get('name') or '')
    return rows[:limit] if limit else rows
