#!/usr/bin/env python
"""design/_session/workflow_gate.py - the Trading Session WORKFLOW acceptance gate, one command.

    python design/_session/workflow_gate.py            # run it, write workflow-report.md
    python design/_session/workflow_gate.py --keep     # same, but keep the throwaway dir

What it does, in order:
  1. makes a THROWAWAY data dir and seeds it with the payloads the session queue is built from
     (trader_plan.json, report.json, run_queue.json, trader_limits.json, plat_history.json)
  2. boots a real dashboard server on a free port with WFM_DATA pointing at that dir
  3. runs design/_session/workflow_gate.js (puppeteer-core), which drives the REAL UI through
     Whisper -> CONTACTED -> the reconcile check -> Confirm, reading every claim back from the
     DOM, from the app's own HTTP answers and from the store files on disk
  4. tears the server down, merges the driver's result into design/_session/workflow-report.md,
     prints the PASS/FAIL verdict with the observed evidence, and exits 0/1

WHAT IT DOES NOT DO, ON PURPOSE (all of it repeated in the report)
  - it never touches the repo's real data/: the server is booted with WFM_ROOT=<repo> (so the real
    static/ and scripts/ serve the page) and WFM_DATA=<throwaway>, and the boot script prints
    GATE_DATA so the run can prove which dir the server actually used.
  - it never sends a real whisper to a real player. scripts/whisper.py types the line into a
    running Warframe window; in a gate run the boot script replaces ONLY whisper.send() with a
    stub that reports the same success a delivered whisper reports. message()/line()/copy() and
    every line of server.py after them are the real code.
  - it never runs the local pipeline: the confirmation's background sync kick is stubbed out
    (exactly what tests/test_session_api.py does) because scripts/refresh.py + invdiff.py do not
    read WFM_DATA and would rewrite the developer's real data/.
"""
import argparse
import json
import os
import shutil
import socket
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request
from datetime import datetime

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
DRIVER = os.path.join(HERE, 'workflow_gate.js')
REPORT = os.path.join(HERE, 'workflow-report.md')
CHROME = os.environ.get('WFM_CHROME') or 'C:/Program Files/Google/Chrome/Application/chrome.exe'

# The seeded world. Kept in step with the constants in workflow_gate.js (the driver prints its own
# copy of them under meta.seed, so a drift is visible in the raw result).
SEED = {
    'slug': 'primed_continuity',
    'name': 'Primed Continuity',
    'rank': 0,
    'qty': 3,
    'price': 48,           # the price the whisper is sent at (the run queue's buy_price)
    'copies_before': 4,    # report.json sellable_count before the sale
    'copies_after': 1,     # ... and after it (3 copies left = the 3 that were asked for)
    'plat_before': 1220,
    'plat_after': 1220 + 3 * 48,
    'buyer': 'GateBuyer',  # a name that exists nowhere but this fixture
    'account': 'GateAccount',
}

BOOT_TEMPLATE = '''# generated by design/_session/workflow_gate.py - the gate's own server process. Not part of the
# repo: it lives in the throwaway dir and is deleted with it.
import os, sys, threading

REPO = @@REPO@@
sys.path.insert(0, os.path.join(REPO, 'scripts'))

# 1) THE WHISPER TRANSPORT ONLY. There is no Warframe window in a gate run, and a gate must never
#    type a real whisper at a real player, so whisper.send() - the Windows keystroke path - is
#    replaced by a stub that reports exactly what a delivered whisper reports (True, R_SENT).
#    whisper.message()/line()/copy() and every line of server.py after them are the real code.
import whisper as _w
def _gate_send(text, item=None, price=None, kind=None, user=None):
    return True, getattr(_w, 'R_SENT', 'sent')
_w.send = _gate_send
sys.modules['whisper'] = _w

# 2) Load server.py as a module (its own __main__ block is run by hand below) so the confirmation's
#    background sync kick can be neutralised before the server starts listening.
path = os.path.join(REPO, 'server.py')
g = {'__name__': 'gate_server', '__file__': path, '__builtins__': __builtins__}
exec(compile(open(path, encoding='utf-8').read(), path, 'exec'), g)

# 3) The sync kick after a confirmation runs scripts/refresh.py + invdiff.py + progress.py with
#    cwd=REPO. Those scripts do not read WFM_DATA, so a real kick would rewrite the developer's
#    real data/. tests/test_session_api.py stubs _kick_sync for the same reason; the confirmation
#    transaction itself - trade_log, the session state, the cursor - is untouched by this.
g['_kick_sync'] = lambda *a, **k: None

print('GATE_DATA=' + g['DATA'], flush=True)
print('GATE_ROOT=' + g['ROOT'], flush=True)
print('GATE_WHISPER=stubbed', flush=True)
srv = g['ThreadingHTTPServer']((g['HOST'], g['PORT']), g['H'])
threading.Thread(target=g['autosync_loop'], daemon=True).start()
print('gate server on http://%s:%s/' % (g['HOST'], g['PORT']), flush=True)
srv.serve_forever()
'''


def boot_source():
    """The gate's server bootstrap, with this checkout's repo path baked in (never hardcoded)."""
    return BOOT_TEMPLATE.replace('@@REPO@@', repr(REPO.replace('\\', '/')))


def jwrite(path, obj):
    with open(path, 'w', encoding='utf-8') as fh:
        json.dump(obj, fh, indent=1)


def seed_data(data):
    """The payloads the session queue, the buyer row and the reconcile check are built from."""
    jwrite(os.path.join(data, 'trader_plan.json'), {
        'generated': datetime.now().astimezone().isoformat(), 'dry_run': True,
        'plan': [{'slug': SEED['slug'], 'name': SEED['name'], 'per_trade': SEED['qty'],
                  'price': SEED['price'], 'rank': SEED['rank'], 'lane': 'rank %d' % SEED['rank']}]})
    jwrite(os.path.join(data, 'report.json'), {
        'totals': {'sellable': SEED['copies_before']},
        'sell_now': [{'slug': SEED['slug'], 'name': SEED['name'], 'cat': 'mod',
                      'lane_rank': SEED['rank'], 'lane_ask': 60, 'wts': 70, 'wtb': 45,
                      'vol48': 110, 'n_buy': 5, 'sellable_count': SEED['copies_before']}]})
    # The row names its lane, exactly as the real producer writes it now: a lane is what pairs a
    # buyer with a row, and a run-queue row without one is deliberately not actionable.
    jwrite(os.path.join(data, 'run_queue.json'), {
        'queue': [{'slug': SEED['slug'], 'lane': 'rank %d' % SEED['rank'], 'rank': SEED['rank'],
                   'qty': SEED['qty'], 'my_price': SEED['price'],
                   'buyer': SEED['buyer'], 'buyer_status': 'ingame', 'buy_price': SEED['price'],
                   'why': 'seeded by workflow_gate.py'}],
        'summary': {'ingame': 1, 'online': 0, 'total': 1}})
    jwrite(os.path.join(data, 'trader_limits.json'), {
        'plat': SEED['plat_before'], 'account': SEED['account'], 'trades_left': 6,
        'trade_cap': 20, 'ts': 0})
    jwrite(os.path.join(data, 'plat_history.json'),
           [{'ts': int(time.time()) - 3600, 'plat': SEED['plat_before']}])


def git_facts():
    """The revision the result belongs to. A harness that reports on a working tree has to say
    which working tree."""
    def run(args):
        try:
            p = subprocess.run(['git'] + args, cwd=REPO, capture_output=True, text=True, timeout=30)
            return (p.stdout or '').strip()
        except Exception:
            return ''
    dirty = run(['status', '--porcelain']).splitlines()
    return {'rev': run(['rev-parse', '--short', 'HEAD']) or '?',
            'dirty': '; '.join(x.strip() for x in dirty)[:300],
            'files_changed': len(dirty)}


def real_snapshot():
    """Informational only: the repo's real data/ files this gate could plausibly disturb.
    The developer's own supervised app may write them at any time, so this is reported as a fact,
    never asserted."""
    out = {}
    for name in ('trade_session.json', 'trade_log.json', 'whisper_log.json', 'report.json',
                 'plat_history.json', 'trader_limits.json', 'sync_log.json'):
        p = os.path.join(REPO, 'data', name)
        try:
            st = os.stat(p)
            out[name] = {'exists': True, 'bytes': st.st_size, 'mtime': int(st.st_mtime)}
        except OSError:
            out[name] = {'exists': False}
    return out


def free_port():
    s = socket.socket()
    s.bind(('127.0.0.1', 0))
    port = s.getsockname()[1]
    s.close()
    return port


def http_json(url, timeout=8):
    try:
        with urllib.request.urlopen(url, timeout=timeout) as r:
            return r.status, json.loads(r.read().decode('utf-8'))
    except urllib.error.HTTPError as e:
        try:
            return e.code, json.loads(e.read().decode('utf-8'))
        except Exception:
            return e.code, None
    except Exception as e:
        return 0, {'error': str(e)[:200]}


def wait_ready(base, proc, log_path, timeout=90):
    """Poll GET /api/session until the gate server answers, or say why it never did."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        if proc.poll() is not None:
            return 'the gate server exited (rc=%s)' % proc.returncode
        code, body = http_json(base + '/api/session', timeout=3)
        if code == 200 and isinstance(body, dict) and body.get('ok') is True:
            return None
        time.sleep(0.4)
    tail = ''
    try:
        tail = open(log_path, encoding='utf-8', errors='replace').read()[-1500:]
    except OSError:
        pass
    return 'the gate server never answered on %s within %ss. log tail:\n%s' % (base, timeout, tail)


def md_table(head, rows):
    out = ['| ' + ' | '.join(str(h) for h in head) + ' |',
           '|' + '|'.join(['---'] * len(head)) + '|']
    for r in rows:
        out.append('| ' + ' | '.join('' if c is None else str(c) for c in r) + ' |')
    return '\n'.join(out)


def esc(s, limit=180):
    return str('' if s is None else s).replace('|', '\\|').replace('\n', ' ')[:limit]


def build_report(raw, launcher, boot_lines, now_local, kept, tmp):
    v = raw.get('verdict', {})
    meta = raw.get('meta', {})
    checks = raw.get('checks', [])
    wf = [c for c in checks if not c.get('diagnostic')]
    dx = [c for c in checks if c.get('diagnostic')]
    failed = [c for c in wf if not c.get('ok')]
    dfail = [c for c in dx if not c.get('ok')]
    L = []
    A = L.append

    A('# WFM Trader — Trading Session WORKFLOW gate')
    A('')
    A('**Run:** %s  ' % now_local)
    A('**Drives:** `Whisper → CONTACTED → reconcile check → Confirm`, through the real UI at %s  '
      % meta.get('base'))
    A('**Server:** `server.py` on the throwaway data dir `%s` (never the repo\'s real `data/`)  '
      % str(meta.get('data')))
    A('**Driver:** `design/_session/workflow_gate.js` (puppeteer-core %s, node %s)  '
      % (str(meta.get('puppeteer')), str(meta.get('node'))))
    A('**Repo revision at run time:** `%s`%s  '
      % (launcher.get('rev', '?'), (', working tree dirty: ' + launcher['dirty']) if launcher.get('dirty') else ''))
    A('')
    A('## Verdict')
    A('')
    if v.get('crashed'):
        A('**FAIL — the driver crashed before it finished:** `%s`' % esc(str(v.get('crashed'))[:300], 300))
    else:
        A('**%s — %s of %s workflow checks passed**%s.'
          % ('PASS' if v.get('pass') else 'FAIL', len(wf) - len(failed), len(wf),
             ('; %s of %s labelled diagnostic check(s) failed' % (len(dfail), len(dx))) if dx else ''))
    A('')
    if failed:
        A('### Failing checks (the honest current state)')
        A('')
        for c in failed:
            A('- **%s — %s**' % (c.get('step'), c.get('title')))
            A('  - expected: `%s`' % esc(c.get('expected'), 300))
            A('  - observed: `%s`' % esc(c.get('observed'), 300))
            if c.get('note'):
                A('  - note: %s' % esc(c.get('note'), 300))
        A('')

    A('## What it drove, and what it saw')
    A('')
    A('The fixture (written into the throwaway dir by this launcher, and nothing else is in it):')
    A('')
    A(md_table(['fact', 'value'], [
        ['queue item', '`%s` (rank %s)' % (SEED['slug'], SEED['rank'])],
        ['stack and price the loop lists', '%s copies at %sp (plan `per_trade`/`price`)'
         % (SEED['qty'], SEED['price'])],
        ['buyer the run queue names', '`%s` (buy_price %sp)' % (SEED['buyer'], SEED['price'])],
        ['stack before the sale (report.json)', SEED['copies_before']],
        ['stack after the sale (report.json)', SEED['copies_after']],
        ['platinum before → after', '%s → %s (+%s = %s × %sp)'
         % (SEED['plat_before'], SEED['plat_after'], SEED['qty'] * SEED['price'], SEED['qty'], SEED['price'])],
        ['account the payload must name', '`%s` (proof the server read the throwaway dir)' % SEED['account']],
    ]))
    A('')
    steps = []
    for c in checks:
        if c.get('step') not in steps:
            steps.append(c.get('step'))
    A(md_table(['step', 'checks', 'failed'],
               [[s, len([c for c in checks if c['step'] == s]),
                 len([c for c in checks if c['step'] == s and not c['ok']])] for s in steps]))
    A('')
    A('### Every check, expected vs observed')
    A('')
    A('Workflow checks (these decide the verdict) come first; labelled DIAGNOSTIC rows (see the '
      'section after) never decide it.')
    A('')
    A(md_table(['step', 'check', 'kind', 'ok', 'expected', 'observed'],
               [[c.get('step'), esc(c.get('title'), 90), 'DIAGNOSTIC' if c.get('diagnostic') else 'workflow',
                 'yes' if c.get('ok') else '**NO**',
                 esc(c.get('expected'), 130), esc(c.get('observed'), 200)] for c in checks]))
    A('')
    notes = [c for c in checks if c.get('note')]
    if notes:
        A('Notes the driver attached to specific checks:')
        A('')
        for c in notes:
            A('- **%s** — %s' % (esc(c.get('title'), 90), esc(c.get('note'), 300)))
        A('')
    if dx:
        A('### Diagnostics (do not decide the verdict)')
        A('')
        A('These exist to separate "the app is broken" from "the check is broken", and every one of '
          'them is labelled in the output. A diagnostic only ever runs after a workflow check has '
          'already failed, and it changes exactly one thing — the shim below — which is stated with '
          'the result.')
        A('')
        for c in dx:
            A('- **%s — %s**: %s' % (c.get('step'), c.get('title'),
                                     'passes' if c.get('ok') else '**fails**'))
            A('  - expected: `%s`' % esc(c.get('expected'), 300))
            A('  - observed: `%s`' % esc(c.get('observed'), 300))
            if c.get('note'):
                A('  - note: %s' % esc(c.get('note'), 300))
        A('')
        shim = ((raw.get('evidence', {}).get('reconcile') or {}).get('diagnostic_shim') or {})
        if shim:
            A('The shim a diagnostic used, verbatim (`page.evaluate` in the page, nothing else '
              'changed in the panel):')
            A('')
            A('```js')
            A('const orig = window.sessionPayload;             // static/session.js')
            A('window.sessionPayload = function () {')
            A('  const P = orig();')
            A('  const S = (FEAT && FEAT.session) || {};')
            A('  P.proposals = S.proposals || [];              // the key renderSession() already reads')
            A('  P.needs_you = S.needs_you || 0;')
            A('  return P;')
            A('};')
            A('renderSession();                                // the panel\'s own painter')
            A('```')
            A('')
            A('Result of the shim: `%s`' % esc(str(shim.get('sessionPayload_forwarding')), 120))
            A('')

    A('## Evidence, read back')
    A('')
    A('Each block is what the driver actually read — DOM text the panel painted, the app\'s own '
      'HTTP answers (fetched through the page, same origin), and the store files on disk.')
    A('')
    for name in ('load', 'start', 'whisper', 'reconcile', 'confirm', 'confirm_probe'):
        if name not in raw.get('evidence', {}):
            continue
        A('### %s' % name)
        A('')
        A('```json')
        A(json.dumps(raw['evidence'][name], indent=1, sort_keys=False)[:6000])
        A('```')
        A('')
    obs = raw.get('observations') or []
    if obs:
        A('### Other things the drive showed (not part of the verdict)')
        A('')
        A('Smaller inconsistencies the same run happened to produce. They are recorded because the '
          'drive saw them, and they are not asserted anywhere.')
        A('')
        for o in obs:
            A('- **%s**' % esc(o.get('what'), 300))
            A('  - where: %s' % esc(o.get('where'), 300))
            A('  - saw: `%s`' % esc(o.get('saw'), 300))
        A('')
    if raw.get('console'):
        A('### Console errors / page errors')
        A('')
        A('```json')
        A(json.dumps(raw['console'][:10], indent=1)[:2000])
        A('```')
        A('')
    hyg = (raw.get('evidence', {}) or {}).get('hygiene') or {}
    if hyg:
        A('### Connection-level failures (the documented net-stack class, rechecked)')
        A('')
        A('Chromium refusing a burst is not an application failure. The rule is the release gate\'s '
          '(`design/_stage10/gate.js`): a request only counts against the app if it failed in Chromium '
          '**and** still fails (or answers 4xx/5xx) when asked again from node. The rows are reported '
          'either way.')
        A('')
        if hyg.get('rechecks'):
            A(md_table(['step', 'url', 'chromium failure', 'direct recheck', 'verdict'],
                       [[r.get('step'), esc(r.get('url'), 120), esc(r.get('why'), 60),
                         r.get('recheck_status') if r.get('recheck_status') else ('err: ' + esc(r.get('recheck_error'), 60)),
                         'cleared (does not count)' if (r.get('recheck_status') and r.get('recheck_status') < 400)
                         else 'STILL FAILING'] for r in hyg['rechecks']]))
        else:
            A('None: no request failed at the connection level during this run.')
        A('')
        ct = hyg.get('console_transient') or []
        if ct:
            A('Console/page rows classified as that class (each still printed, none hidden):')
            A('')
            A(md_table(['step', 'text', 'why'],
                       [[c.get('step'), esc(c.get('text'), 120), esc(c.get('classified') or 'matches the net-stack code class', 120)]
                        for c in ct]))
            A('')
        A('Blocked-CDN requests excluded (missing card/warframe art, counted, never hidden): %d'
          % len(hyg.get('blocked_cdn') or []))
        A('')
    if raw.get('failed_requests'):
        A('### Failed requests (outside the blocked-CDN class)')
        A('')
        A('```json')
        A(json.dumps(raw['failed_requests'][:10], indent=1)[:2000])
        A('```')
        A('')

    A('## Harness facts')
    A('')
    A(md_table(['fact', 'value'], launcher.get('facts', [])))
    A('')
    if boot_lines:
        A('Gate server stdout (the boot script proving which data dir it used):')
        A('')
        A('```')
        for ln in boot_lines[-8:]:
            A(ln)
        A('```')
        A('')
    if launcher.get('real_data_before'):
        A('The repo\'s REAL `data/` files, before → after (informational only: the developer\'s own '
          'supervised app may write them at any time, so no claim is made from this):')
        A('')
        rows = []
        for k, b in launcher['real_data_before'].items():
            a = (launcher.get('real_data_after') or {}).get(k, {})
            rows.append([k, ('%s bytes @%s' % (b.get('bytes'), b.get('mtime'))) if b.get('exists') else 'absent',
                         ('%s bytes @%s' % (a.get('bytes'), a.get('mtime'))) if a.get('exists') else 'absent',
                         'same' if b == a else 'CHANGED'])
        A(md_table(['file', 'before', 'after', 'verdict'], rows))
        A('')

    A('## What this gate does NOT prove')
    A('')
    A('- **The whisper transport.** `scripts/whisper.py` types the line into a running Warframe '
      'window. There is no game window in a gate run, and a gate must never send a real whisper to '
      'a real player, so the gate server replaces ONLY `whisper.send()` with a stub that reports '
      '`(True, R_SENT)`. The message/line/copy build, the `POST /api/whisper` route, the '
      '`sent → contact()` branch and everything after it are the real code, but the last '
      'centimetre — keystrokes into the game — is not exercised here.')
    A('- **The game\'s side of reconciliation.** The change a sale makes (one stack shorter, '
      'platinum higher) is written by the driver straight into the throwaway `report.json` / '
      '`plat_history.json` that `scripts/report.py` and `scripts/snapshot_plat.py` would normally '
      'write. The snapshot at contact, `propose()`, the check\'s evidence and the confirm are the '
      'real code.')
    A('- **The post-confirm pipeline.** The confirmation\'s background sync kick '
      '(`scripts/refresh.py` + `invdiff.py` + `progress.py`) is stubbed to a no-op: those scripts '
      'do not read `WFM_DATA` and would rewrite the developer\'s real `data/`. The confirmation '
      'transaction itself (trade_log entry, session totals, queue/pending state, cursor) is what '
      'is measured here, and it is unaffected. `tests/test_session_api.py` stubs the same '
      'function.')
    A('- **The auto-sync thread.** It is started the way the real server starts it, but '
      '`data/config.json` says `auto_refresh_seconds: 0`, so the server-side pipeline never runs '
      'during a gate run.')
    A('- **Nothing about the network.** The session loop takes no network path; the gate does not '
      'test warframe.market, prices or the order book.')
    A('')
    A('---')
    A('')
    A('Re-run, one command:')
    A('')
    A('```')
    A('python design/_session/workflow_gate.py')
    A('```')
    A('')
    A('It makes its own throwaway data dir, boots the dashboard against it on a free port, drives '
      'the browser, tears the server down and rewrites this file. `--keep` leaves the throwaway '
      'dir (and the driver\'s raw JSON) on disk for inspection.')
    if kept:
        A('')
        A('This run kept its dir: `%s`' % tmp)
    return '\n'.join(L) + '\n'


def main():
    ap = argparse.ArgumentParser(description='Trading Session workflow acceptance gate')
    ap.add_argument('--keep', action='store_true', help='keep the throwaway data dir + raw JSON')
    args = ap.parse_args()

    now_local = datetime.now().astimezone().strftime('%Y-%m-%d %H:%M:%S %z')
    launcher = {'facts': [], 'real_data_before': real_snapshot(), 'real_data_after': None}
    launcher.update(git_facts())
    tmp = tempfile.mkdtemp(prefix='wfm-workflow-gate-')
    data = os.path.join(tmp, 'data')
    os.makedirs(data)
    raw = {}
    boot_lines = []
    node_out = ''
    proc = None
    port = free_port()
    base = 'http://127.0.0.1:%d' % port
    try:
        print('[1/5] seeding the throwaway data dir: %s' % data)
        seed_data(data)
        # data/config.json for the gate server: the auto-refresh knob controls the app's own poll
        # cadence (what the reconcile check rides). 0 keeps the server-side pipeline off; the page
        # treats 0 as "no value" and polls every 30s, which is what this run waits for.
        jwrite(os.path.join(data, 'config.json'),
               {'port': port, 'host': '127.0.0.1', 'auto_refresh_seconds': 0, 'gamenews_cache_seconds': 86400})
        boot = os.path.join(tmp, '_gate_boot.py')
        with open(boot, 'w', encoding='utf-8') as fh:
            fh.write(boot_source())

        print('[2/5] booting the dashboard on %s (WFM_DATA=%s)' % (base, data))
        env = dict(os.environ)
        env.update({'WFM_ROOT': REPO, 'WFM_DATA': data, 'WFM_PORT': str(port), 'WFM_HOST': '127.0.0.1',
                    'WFM_CONFIG': os.path.join(data, 'config.json'), 'WFM_SYNC_SLICE': '5',
                    'PYTHONIOENCODING': 'utf-8'})
        server_log = os.path.join(tmp, 'gate-server.log')
        sink = open(server_log, 'wb')
        proc = subprocess.Popen([sys.executable, boot], cwd=REPO, env=env,
                                stdout=sink, stderr=subprocess.STDOUT)

        deadline = time.time() + 90
        code, body = 0, None
        while time.time() < deadline:
            if proc.poll() is not None:
                break
            code, body = http_json(base + '/api/session', timeout=3)
            if code == 200 and isinstance(body, dict) and body.get('ok') is True:
                break
            time.sleep(0.4)
        try:
            sink.flush()
            sink.close()
        except Exception:
            pass
        try:
            with open(server_log, encoding='utf-8', errors='replace') as fh:
                out = fh.read()
        except OSError:
            out = ''
        boot_lines = [ln.strip() for ln in out.splitlines() if ln.strip()]
        if code != 200:
            raise RuntimeError('the gate server never answered on %s. log tail:\n%s' % (base, out[-1500:]))

        got_data = next((l.split('=', 1)[1] for l in boot_lines if l.startswith('GATE_DATA=')), '')
        got_whisper = next((l.split('=', 1)[1] for l in boot_lines if l.startswith('GATE_WHISPER=')), '')
        launcher['facts'].append(['server booted against the throwaway data dir',
                                  'yes' if os.path.normcase(os.path.abspath(got_data)) ==
                                  os.path.normcase(os.path.abspath(data)) else
                                  'NO — GATE_DATA=%s' % got_data])
        launcher['facts'].append(['whisper transport', 'stubbed (GATE_WHISPER=%s)' % (got_whisper or '?')])
        launcher['facts'].append(['the queue the server BUILT from the throwaway payloads',
                                  ', '.join(str(r.get('slug')) for r in (body or {}).get('suggested') or [])
                                  or '(none - the payloads were not read)'])

        print('[3/5] driving the browser (Whisper -> CONTACTED -> check -> Confirm) ...')
        raw_path = os.path.join(tmp, 'workflow-raw.json')
        nenv = dict(env)
        nenv.update({'WFM_BASE': base, 'WFM_DATA': data, 'WFM_RAW': raw_path,
                     'WFM_PROFILE': os.path.join(tmp, 'chrome-profile'), 'WFM_CHROME': CHROME,
                     'WFM_SLUG': SEED['slug']})
        spawned = time.time()
        p = subprocess.run(['node', DRIVER], cwd=REPO, env=nenv, capture_output=True, text=True,
                           timeout=600)
        node_out = (p.stdout or '') + (('\n' + p.stderr) if p.stderr else '')
        print('  node rc=%s in %ss' % (p.returncode, round(time.time() - spawned, 1)))
        for ln in (p.stdout or '').strip().splitlines():
            print('  ' + ln)

        print('[4/5] merging the result into %s ...' % os.path.basename(REPORT))
        raw = json.load(open(raw_path, encoding='utf-8')) if os.path.isfile(raw_path) else {}
        if not raw:
            raw = {'verdict': {'pass': False, 'crashed': 'the driver wrote no raw result:\n' + node_out[-1500:]},
                   'checks': [], 'meta': {}, 'evidence': {}}
        launcher['real_data_after'] = real_snapshot()
        # proof the session the driver drove lives in the throwaway dir, read from the driver's
        # own evidence rather than asserted here
        ev = raw.get('evidence', {})
        sess = (ev.get('start') or {}).get('session') or {}
        pend = ((ev.get('whisper') or {}).get('pending') or [{}])[0]
        launcher['facts'].append(['the session the driver started names the fixture account',
                                  '`%s` (plat_start=%s)' % (sess.get('account'), sess.get('plat_start'))
                                  if sess.get('account') == SEED['account'] else
                                  'NO — account=%r' % sess.get('account')])
        launcher['facts'].append(['the CONTACTED snapshot the server took',
                                  'id=%s state=%s copies=%s plat=%s asked=%sp x%s'
                                  % (pend.get('id'), pend.get('state'), pend.get('inv_before'),
                                     pend.get('plat_before'), pend.get('expected_plat'), pend.get('qty'))])
        launcher['facts'].append(['the trade the Confirm click wrote',
                                  json.dumps((((ev.get('confirm') or ev.get('confirm_probe') or {})
                                               .get('trade_log') or [{}])[0]))[:220]])
        md = build_report(raw, launcher, boot_lines, now_local, args.keep, tmp)
        with open(REPORT, 'w', encoding='utf-8') as fh:
            fh.write(md)
        print('  %s bytes -> %s' % (len(md), REPORT))
    finally:
        if proc is not None and proc.poll() is None:
            proc.terminate()
            try:
                proc.wait(timeout=10)
            except Exception:
                proc.kill()
        if not args.keep:
            shutil.rmtree(tmp, ignore_errors=True)
        else:
            print('kept: %s' % tmp)

    checks = raw.get('checks', [])
    failed = [c for c in checks if not c.get('ok')]
    ok = bool(raw.get('verdict', {}).get('pass')) and not failed
    print('[5/5] verdict')
    for c in checks:
        print('  %s [%s] %s' % ('ok  ' if c.get('ok') else 'FAIL', c.get('step'), c.get('title')))
        if not c.get('ok'):
            print('       expected: %s' % c.get('expected'))
            print('       observed: %s' % c.get('observed'))
    if raw.get('verdict', {}).get('crashed'):
        print('  CRASH: %s' % str(raw['verdict']['crashed'])[:400])
    print('WORKFLOW %s - %d of %d checks' % ('PASS' if ok else 'FAIL',
                                             len(checks) - len(failed), len(checks)))
    sys.exit(0 if ok else 1)


if __name__ == '__main__':
    main()
