#!/usr/bin/env python3
"""make_preview.py - build the README preview asset (animated GIF) and the page screenshots.

It drives the ALREADY-RUNNING local dashboard (default http://127.0.0.1:8787) with
headless Chrome through puppeteer-core, walks one fixed tour and grabs a frame every
~700 ms while it goes:

    home  ->  trader (safety)  ->  settings (guardrails)  ->  [theme switch]  ->  market  ->
    collection  ->  cards

A second, quieter pass also saves one full-size still per page into assets/ (used as the
README screenshots). Frames land in tools/preview_frames/ (gitignored intermediate) and the
animation is assembled into assets/preview.gif.

Assembly order (first tool that exists wins):
  1. ffmpeg          -> GIF, palettegen/paletteuse, default 960 px wide @ 8 fps, <= 4 MB
                        (the size budget is enforced by stepping down quality tiers)
  2. Pillow          -> animated WebP + APNG at the same width/fps
  3. neither         -> frames are kept and tools/preview_frames/BUILD_GIF.md is written
                        with the exact ffmpeg command to build the GIF later

Dependencies (none of them Python packages - this script itself is stdlib-only):
  * node          (v18+; `node --version`)
  * puppeteer-core  default C:/Users/<you>/AppData/Local/Temp/shotkit/node_modules/puppeteer-core
  * Chrome        default C:/Program Files/Google/Chrome/Application/chrome.exe
  * ffmpeg or Pillow, only for the assembly step
Override any of them with --node / --chrome / --puppeteer-core or the env vars
WFM_NODE, WFM_CHROME, WFM_PUPPETEER_CORE (and WFM_PREVIEW_URL for the dashboard URL).

Usage:
  python server.py                                        # in another shell: keep it running
  python tools/make_preview.py                            # posters + tour + GIF
  python tools/make_preview.py --skip-posters             # GIF only (faster)
  python tools/make_preview.py --url http://127.0.0.1:8787 --cadence 700
  python tools/make_preview.py --width 960 --fps 8 --max-mb 4
  python tools/make_preview.py --assemble pillow          # force the Pillow path
  python tools/make_preview.py --only-frames              # capture, do not assemble
  python tools/make_preview.py --scrub "Handle,Name"      # blur names in every capture
  python tools/make_preview.py --selftest                 # offline checks, no browser

Screenshots of a real account: put the handles you never want published in
tools/preview_frames/redact.txt (one per line - that directory is gitignored, nothing in it
is committed) or pass --scrub "Handle,Name". Every capture blurs those words first. This file
itself must never name an account.

Exit codes: 0 ok | 1 capture/assembly failure | 2 missing prerequisite or bad usage
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import re
import shutil
import struct
import subprocess
import sys
import time
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
FRAMES = os.path.join(HERE, 'preview_frames')
ASSETS = os.path.join(ROOT, 'assets')
DEFAULT_URL = os.environ.get('WFM_PREVIEW_URL', 'http://127.0.0.1:8787')

# Account handles / names that must never appear in a published screenshot. Blurred (whole
# word, case-insensitive) in the page before every capture. The list is deliberately NOT
# hard-coded here - this file is public. Names come from, in order: --scrub, the env var
# WFM_PREVIEW_SCRUB, then tools/preview_frames/redact.txt (one name per line, '#' comments;
# that whole directory is gitignored, so your handles stay on your machine).
PUPPETEER_CANDIDATES = [
    os.environ.get('WFM_PUPPETEER_CORE') or '',
    os.path.join(os.environ.get('LOCALAPPDATA', ''), 'Temp', 'shotkit', 'node_modules', 'puppeteer-core'),
    os.path.join(ROOT, 'node_modules', 'puppeteer-core'),
]

CHROME_CANDIDATES = [
    os.environ.get('WFM_CHROME') or '',
    os.path.join(os.environ.get('PROGRAMFILES', 'C:/Program Files'), 'Google', 'Chrome', 'Application', 'chrome.exe'),
    os.path.join(os.environ.get('PROGRAMFILES(X86)', 'C:/Program Files (x86)'), 'Google', 'Chrome', 'Application', 'chrome.exe'),
    os.path.join(os.environ.get('LOCALAPPDATA', ''), 'Google', 'Chrome', 'Application', 'chrome.exe'),
    os.path.join(os.environ.get('PROGRAMFILES(X86)', 'C:/Program Files (x86)'), 'Microsoft', 'Edge', 'Application', 'msedge.exe'),
    os.path.join(os.environ.get('PROGRAMFILES', 'C:/Program Files'), 'Microsoft', 'Edge', 'Application', 'msedge.exe'),
]

# --------------------------------------------------------------------------------------- #
# driver template (token __CFG_JSON__ is replaced with the run config)                      #
# --------------------------------------------------------------------------------------- #
DRIVER_CJS = r"""'use strict';
/* generated by tools/make_preview.py - rewritten on every run, do not edit */
const CFG = __CFG_JSON__;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

const diag = {};
const posters = [];
const pageErrors = [];
const failedReqs = [];
let shots = 0;

const pad = (n) => String(n).padStart(3, '0');

/* blur any text node containing one of CFG.scrub (whole-word, case-insensitive) */
async function scrub(page) {
  if (!CFG.scrub || !CFG.scrub.length) return 0;
  return page.evaluate((names) => {
    const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const rx = new RegExp('\\b(' + names.map(esc).join('|') + ')\\b', 'gi');
    const skip = { SCRIPT: 1, STYLE: 1, TEXTAREA: 1, NOSCRIPT: 1 };
    const walker = document.createTreeWalker(document.documentElement, NodeFilter.SHOW_TEXT, null);
    const targets = [];
    let t;
    while ((t = walker.nextNode())) {
      const p = t.parentElement;
      if (!p || skip[p.tagName] || p.hasAttribute('data-scrubbed')) continue;
      rx.lastIndex = 0;
      if (t.nodeValue && rx.test(t.nodeValue)) targets.push(t);
    }
    let hits = 0;
    for (const node of targets) {
      const s = node.nodeValue || '';
      const frag = document.createDocumentFragment();
      let last = 0;
      let m;
      rx.lastIndex = 0;
      while ((m = rx.exec(s)) !== null) {
        if (m.index > last) frag.appendChild(document.createTextNode(s.slice(last, m.index)));
        const span = document.createElement('span');
        span.setAttribute('data-scrubbed', '1');
        span.style.filter = 'blur(6px)';
        span.textContent = m[0];
        frag.appendChild(span);
        last = m.index + m[0].length;
        hits++;
      }
      if (last < s.length) frag.appendChild(document.createTextNode(s.slice(last)));
      if (node.parentNode) node.parentNode.replaceChild(frag, node);
    }
    return hits;
  }, CFG.scrub);
}

/* capture one frame, then idle until the next ~CADENCE tick, for `ms` milliseconds */
async function hold(page, ms, label) {
  const end = Date.now() + ms;
  let n = 0;
  diag['path_' + label] = await page.evaluate(() => location.pathname + location.hash).catch(() => '?');
  for (;;) {
    const t0 = Date.now();
    await scrub(page);
    await page.screenshot({ path: CFG.frames + '/frame_' + pad(shots) + '.png' });
    shots++;
    n++;
    if (Date.now() >= end) break;
    await sleep(Math.max(0, CFG.cadence - (Date.now() - t0)));
  }
  diag[label] = (diag[label] || 0) + n;
}

async function poster(page, file) {
  await scrub(page);
  await page.screenshot({ path: CFG.assets + '/' + file });
  posters.push(file);
}

async function settleHome(page) {
  await page.waitForFunction("document.querySelectorAll('#kpis > *').length > 0", { timeout: 20000 })
    .catch(() => { diag.home_no_kpis = 1; });
  await sleep(1000);
}

async function settleTrader(page) {
  await page.waitForFunction("document.querySelectorAll('#killList > *').length > 0", { timeout: 20000 })
    .catch(() => { diag.trader_no_kill = 1; });
  await sleep(500);
}

async function settleSettings(page) {
  await page.waitForFunction("document.querySelectorAll('#cfgList .cfgrow').length >= 5", { timeout: 20000 })
    .catch(() => { diag.settings_no_rows = 1; });
  await sleep(500);
}

async function settleCollection(page) {
  await page.waitForFunction("(document.getElementById('grid') || { children: [] }).children.length > 0", { timeout: 25000 })
    .catch(() => { diag.collection_empty = 1; });
  await sleep(1000);
}

async function settleCards(page) {
  await page.waitForFunction("document.querySelectorAll('.mcd-card').length > 20", { timeout: 30000 })
    .catch(() => { diag.cards_few = 1; });
  await sleep(1500);
}

const counts = () => ({
  kpis: document.querySelectorAll('#kpis > *').length,
  cfgRows: document.querySelectorAll('#cfgList > *').length,
  dealRows: document.querySelectorAll('#dealsList > *').length,
  collTiles: (document.getElementById('grid') || { children: [] }).children.length,
  cards: document.querySelectorAll('.mcd-card').length,
  scrubbed: document.querySelectorAll('[data-scrubbed]').length,
});

(async () => {
  const puppeteer = require(CFG.puppeteer);
  const browser = await puppeteer.launch({
    executablePath: CFG.chrome,
    headless: true,
    args: ['--no-sandbox', '--disable-gpu', '--hide-scrollbars', '--mute-audio',
           '--force-device-scale-factor=1', '--force-color-profile=srgb', '--disable-extensions'],
  });
  const page = await browser.newPage();
  page.setDefaultTimeout(20000);
  page.on('pageerror', (e) => pageErrors.push(String(e.message).slice(0, 160)));
  page.on('requestfailed', (r) => { if (failedReqs.length < 12) failedReqs.push(r.url().slice(0, 100)); });
  page.on('console', (m) => { if (m.type() === 'error' && pageErrors.length < 12) pageErrors.push(m.text().slice(0, 160)); });

  /* ---------------- pass 1: one still per page, straight at the top ---------------- */
  if (CFG.posters) {
    await page.setViewport({ width: CFG.poster_w, height: CFG.poster_h, deviceScaleFactor: 1 });

    await page.goto(CFG.url + '/', { waitUntil: 'domcontentloaded', timeout: 60000 });
    await settleHome(page);
    await poster(page, 'shot_home.png');

    await page.evaluate(() => { location.hash = '#trader'; });
    await settleTrader(page);
    await page.evaluate(() => window.scrollTo(0, 0));
    await sleep(400);
    await poster(page, 'shot_trader.png');

    await page.goto(CFG.url + '/settings.html', { waitUntil: 'domcontentloaded', timeout: 60000 });
    await settleSettings(page);
    await page.evaluate(() => {
      const el = document.getElementById('cfgList');
      if (el) (el.closest('.card') || el).scrollIntoView({ block: 'start' });
    });
    await sleep(500);
    await poster(page, 'shot_settings.png');

    await page.goto(CFG.url + '/#market', { waitUntil: 'domcontentloaded', timeout: 60000 });
    await page.waitForFunction(
      "(() => { const v = document.getElementById('view-market'); return !!v && !v.classList.contains('hidden') && document.querySelectorAll('#dealsList > *').length > 3; })()",
      { timeout: 20000 }).catch(() => { diag.market_no_deals = 1; });
    await page.evaluate(() => window.scrollTo(0, 0));
    await sleep(500);
    await poster(page, 'shot_market.png');

    await page.goto(CFG.url + '/cards.html', { waitUntil: 'domcontentloaded', timeout: 60000 });
    await settleCards(page);
    await poster(page, 'shot_cards.png');
  }

  /* ---------------- pass 2: the animated tour ---------------- */
  await page.setViewport({ width: CFG.w, height: CFG.h, deviceScaleFactor: 1 });

  await page.goto(CFG.url + '/', { waitUntil: 'domcontentloaded', timeout: 60000 });
  await settleHome(page);
  await hold(page, CFG.holds.home, 'home');

  await page.evaluate(() => { location.hash = '#trader'; });
  await settleTrader(page);
  await page.evaluate(() => window.scrollTo(0, 0));
  await sleep(400);
  await hold(page, CFG.holds.trader, 'trader');

  await page.goto(CFG.url + '/settings.html', { waitUntil: 'domcontentloaded', timeout: 60000 });
  await settleSettings(page);
  await page.evaluate(() => {
    const el = document.getElementById('cfgList');
    if (el) (el.closest('.card') || el).scrollIntoView({ block: 'start' });
  });
  await sleep(500);
  await hold(page, CFG.holds.guardrails, 'guardrails');

  /* one theme change, for flavour - the rest of the tour plays in the new palette */
  await page.evaluate(() => { const b = document.getElementById('themeBtn'); if (b) b.click(); });
  await sleep(700);
  await page.evaluate((i) => {
    const it = document.querySelectorAll('#themeGrid .theme-item')[i];
    if (it) it.click();
  }, CFG.theme);
  await sleep(600);
  await page.evaluate(() => { const p = document.getElementById('themePanel'); if (p) p.classList.add('hidden'); });
  await sleep(200);
  diag.theme_after = await page.evaluate(() => {
    try { return parseInt(localStorage.getItem('wfm.theme') || '-1', 10); } catch (e) { return -1; }
  });
  await hold(page, CFG.holds.theme, 'theme');

  await page.goto(CFG.url + '/#market', { waitUntil: 'domcontentloaded', timeout: 60000 });
  await page.waitForFunction(
    "(() => { const v = document.getElementById('view-market'); return !!v && !v.classList.contains('hidden') && document.querySelectorAll('#dealsList > *').length > 3; })()",
    { timeout: 20000 }).catch(() => { diag.market_no_deals = 1; });
  await page.evaluate(() => window.scrollTo(0, 0));
  await sleep(500);
  await hold(page, CFG.holds.market, 'market');

  await page.evaluate(() => window.scrollBy(0, 640));
  await sleep(400);
  await hold(page, CFG.holds.market_scroll, 'market_scroll');

  await page.goto(CFG.url + '/collection.html', { waitUntil: 'domcontentloaded', timeout: 60000 });
  await settleCollection(page);
  await hold(page, CFG.holds.collection, 'collection');

  await page.goto(CFG.url + '/cards.html', { waitUntil: 'domcontentloaded', timeout: 60000 });
  await settleCards(page);
  await hold(page, CFG.holds.cards, 'cards');

  diag.final = await page.evaluate(counts).catch(() => null);
  diag.failed_requests = failedReqs;
  await browser.close();
  console.log('PREVIEW_JSON ' + JSON.stringify({ ok: true, frames: shots, posters: posters, diag: diag, pageErrors: pageErrors }));
})().catch((e) => {
  console.log('PREVIEW_JSON ' + JSON.stringify({ ok: false, error: String(e && e.message || e), frames: shots, posters: posters, diag: diag, pageErrors: pageErrors }));
  process.exit(1);
});
"""


# --------------------------------------------------------------------------------------- #
# helpers                                                                                   #
# --------------------------------------------------------------------------------------- #
def say(msg):
    print(msg, flush=True)


def die(msg, code=2):
    say('ERROR: ' + msg)
    sys.exit(code)


def resolve_scrub(explicit):
    """Names to blur: --scrub wins, else WFM_PREVIEW_SCRUB + tools/preview_frames/redact.txt."""
    if explicit is not None:
        return [s.strip() for s in explicit.split(',') if s.strip()]
    names = [s.strip() for s in os.environ.get('WFM_PREVIEW_SCRUB', '').split(',') if s.strip()]
    redact = os.path.join(FRAMES, 'redact.txt')
    if os.path.isfile(redact):
        with open(redact, encoding='utf-8') as f:
            names += [ln.strip() for ln in f if ln.strip() and not ln.lstrip().startswith('#')]
    seen, out = set(), []
    for n in names:
        if n.lower() not in seen:
            seen.add(n.lower())
            out.append(n)
    return out


def which_node(explicit):
    cand = [explicit, os.environ.get('WFM_NODE') or '', shutil.which('node') or '',
            os.path.join(os.environ.get('PROGRAMFILES', 'C:/Program Files'), 'nodejs', 'node.exe')]
    for c in cand:
        if c and os.path.isfile(c):
            return c
    return None


def which_chrome(explicit):
    cand = [explicit] + CHROME_CANDIDATES + [shutil.which('chrome') or '', shutil.which('chrome.exe') or '',
                                             shutil.which('google-chrome') or '', shutil.which('chromium') or '']
    for c in cand:
        if c and os.path.isfile(c):
            return c
    return None


def which_puppeteer(explicit):
    cand = [explicit] + PUPPETEER_CANDIDATES
    for c in cand:
        if not c:
            continue
        if os.path.isfile(os.path.join(c, 'package.json')) and \
           os.path.isfile(os.path.join(c, 'lib', 'puppeteer', 'puppeteer-core.js')):
            return c.replace('\\', '/')
    return None


def server_ok(url, timeout=6):
    import urllib.request
    try:
        with urllib.request.urlopen(url.rstrip('/') + '/', timeout=timeout) as r:
            return r.status == 200
    except Exception:
        return False


def png_size(path):
    try:
        with open(path, 'rb') as f:
            head = f.read(33)
        if head[:8] != b'\x89PNG\r\n\x1a\n':
            return None
        w, h = struct.unpack('>II', head[16:24])
        return (w, h)
    except OSError:
        return None


def make_tiny_png():
    """A real 1x1 PNG, built with stdlib zlib - used by --selftest."""
    def chunk(tag, data):
        return struct.pack('>I', len(data)) + tag + data + struct.pack('>I', zlib.crc32(tag + data) & 0xFFFFFFFF)
    ihdr = struct.pack('>IIBBBBB', 1, 1, 8, 2, 0, 0, 0)
    idat = zlib.compress(b'\x00\x00\x00\x00')
    return b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', ihdr) + chunk(b'IDAT', idat) + chunk(b'IEND', b'')


def tiers(width, fps, colors=256):
    """Quality ladder: keep the GIF under the size budget by stepping quality down."""
    out = [(width, fps, colors)]
    for c in (192, 128):
        out.append((width, fps, c))
    for f2 in (max(5, fps - 2), max(5, fps - 3)):
        out.append((width, f2, 192))
        out.append((width, f2, 128))
    out.append((max(560, int(width * 0.83)), max(5, fps - 2), 160))
    out.append((max(560, int(width * 0.70)), max(5, fps - 2), 128))
    seen, uniq = set(), []
    for t in out:
        if t not in seen:
            seen.add(t)
            uniq.append(t)
    return uniq


def run(cmd, timeout=900):
    p = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    return p.returncode, (p.stdout or ''), (p.stderr or '')


def replace_with_retry(src, dst, tries=6, delay=0.6):
    """Put src at dst. Prefer an atomic os.replace(); on Windows a viewer, sync client or AV can
    hold dst open in a mode that blocks the swap without blocking normal writes, so retry first
    and then fall back to overwriting the file in place. Returns how it landed."""
    last = None
    for _ in range(tries):
        try:
            os.replace(src, dst)
            return 'replaced'
        except PermissionError as e:  # someone else has dst open - wait and retry
            last = e
            time.sleep(delay)
    try:
        shutil.copyfile(src, dst)
        return 'copied-in-place'
    except OSError as e:
        raise PermissionError('%s is locked by another process (%s / %s) - close whatever has it '
                              'open and re-run, or pass --out to write somewhere else'
                              % (dst, last, e))


def have_ffmpeg():
    exe = shutil.which('ffmpeg')
    if not exe:
        return None
    try:
        rc, _, _ = run([exe, '-version'], timeout=30)
        return exe if rc == 0 else None
    except Exception:
        return None


def have_pillow():
    try:
        import PIL  # noqa: F401
        return True
    except Exception:
        return False


def build_driver(cfg, path):
    js = DRIVER_CJS.replace('__CFG_JSON__', json.dumps(cfg, indent=2))
    with open(path, 'w', encoding='utf-8') as f:
        f.write(js)
    return path


def assemble_gif_ffmpeg(ffmpeg, frame_paths, out_path, max_mb, first_w, fps, width):
    pattern = os.path.join(FRAMES, 'frame_%03d.png')
    frames = len(frame_paths)
    scale_w = width
    last = None
    for (w, f, colors) in tiers(width, fps):
        gif_tmp = os.path.join(FRAMES, 'preview_build.gif')
        pal_tmp = os.path.join(FRAMES, 'palette_build.png')
        vf1 = 'scale=%d:-2:flags=lanczos,palettegen=max_colors=%d:stats_mode=diff' % (w, colors)
        rc1, _, err1 = run([ffmpeg, '-y', '-hide_banner', '-loglevel', 'error',
                            '-framerate', str(f), '-i', pattern, '-vf', vf1, pal_tmp])
        if rc1 != 0:
            last = 'palettegen failed: ' + (err1 or '')[-300:]
            continue
        lavfi = 'scale=%d:-2:flags=lanczos[x];[x][1:v]paletteuse=dither=bayer:bayer_scale=3:diff_mode=rectangle' % w
        rc2, _, err2 = run([ffmpeg, '-y', '-hide_banner', '-loglevel', 'error',
                            '-framerate', str(f), '-i', pattern, '-i', pal_tmp,
                            '-lavfi', lavfi, '-loop', '0', gif_tmp])
        if rc2 != 0:
            last = 'paletteuse failed: ' + (err2 or '')[-300:]
            continue
        size = os.path.getsize(gif_tmp)
        if size <= max_mb * 1024 * 1024:
            os.makedirs(os.path.dirname(out_path), exist_ok=True)
            how = replace_with_retry(gif_tmp, out_path)
            return dict(tool='ffmpeg', path=out_path, size=size, width=w, fps=f,
                        colors=colors, frames=frames, duration=frames / float(f),
                        publish=how,
                        note='frame #1 was %dx%d, scaled to %dpx wide' % (first_w[0], first_w[1], w))
        last = '%d px @ %d fps / %d colours = %.2f MB (over budget)' % (w, f, colors, size / 1048576.0)
        say('  ... %s, stepping down' % last)
        scale_w = w
    return dict(tool='ffmpeg', path=None, error=last or 'no tier produced a GIF', width=scale_w, fps=fps, frames=frames)


def assemble_pillow(frame_paths, out_path, width, fps, max_mb):
    from PIL import Image
    frames = []
    for p in frame_paths:
        im = Image.open(p).convert('RGB')
        if im.width != width:
            im = im.resize((width, max(2, int(round(im.height * width / float(im.width))))), Image.LANCZOS)
        frames.append(im)
    duration = int(round(1000.0 / fps))
    written = {}

    def save(img_list, target, **kwargs):
        tmp = target + '.tmp' + os.path.splitext(target)[1]
        os.makedirs(os.path.dirname(os.path.abspath(target)), exist_ok=True)
        img_list[0].save(tmp, save_all=True, append_images=img_list[1:], duration=duration,
                         loop=0, **kwargs)
        replace_with_retry(tmp, target)
        written[os.path.splitext(target)[1].lstrip('.')] = (target, os.path.getsize(target))

    base = os.path.splitext(out_path)[0]
    save(frames, base + '.webp', quality=72, method=4)
    save(frames, base + '.apng')
    if out_path.lower().endswith('.gif'):
        save([f.convert('P', palette=Image.ADAPTIVE, colors=192) for f in frames], out_path)
    return dict(tool='Pillow', path=out_path, width=width, fps=fps, frames=len(frames),
                duration=len(frames) / float(fps), written=written)


def write_build_note(fps, width, max_mb):
    note = os.path.join(FRAMES, 'BUILD_GIF.md')
    pattern = 'tools/preview_frames/frame_%03d.png'
    with open(note, 'w', encoding='utf-8') as f:
        f.write(
            '# no ffmpeg and no Pillow - the GIF was not assembled\n\n'
            'The frames are in `tools/preview_frames/frame_*.png`. To build the animated\n'
            'preview later, install ffmpeg and run:\n\n'
            '```bash\n'
            'ffmpeg -y -framerate %d -i %s -vf "scale=%d:-2:flags=lanczos,palettegen=max_colors=192:stats_mode=diff" palette.png\n'
            'ffmpeg -y -framerate %d -i %s -i palette.png -lavfi "scale=%d:-2:flags=lanczos[x];[x][1:v]paletteuse=dither=bayer:bayer_scale=3:diff_mode=rectangle" -loop 0 assets/preview.gif\n'
            '```\n\n'
            'Then keep it under %.1f MB by lowering the frame rate or the width, and re-run\n'
            '`python tools/make_preview.py` any time (the whole capture is repeatable).\n'
            % (fps, pattern, width, fps, pattern, width, max_mb))
    return note


# --------------------------------------------------------------------------------------- #
# selftest                                                                                  #
# --------------------------------------------------------------------------------------- #
def selftest():
    ok = True

    def chk(name, cond):
        nonlocal ok
        ok = ok and bool(cond)
        say('  %s %s' % ('ok  ' if cond else 'FAIL', name))

    # png_size reads a real PNG built with stdlib only
    tmp = os.path.join(FRAMES, '_selftest.png')
    os.makedirs(FRAMES, exist_ok=True)
    with open(tmp, 'wb') as f:
        f.write(make_tiny_png())
    chk('png_size() reads a stdlib-built 1x1 PNG', png_size(tmp) == (1, 1))
    chk('png_size() rejects a non-PNG', png_size(os.path.abspath(__file__)) is None)

    # driver template renders to valid JSON config
    cfg = dict(url='http://127.0.0.1:8787', cadence=700, w=1440, h=900, theme=14, scrub=['A', 'B'],
               frames=FRAMES, assets=ASSETS, puppeteer='x', chrome='y', posters=True,
               poster_w=1440, poster_h=1000,
               holds=dict(home=1, trader=1, guardrails=1, theme=1, market=1, market_scroll=1,
                          collection=1, cards=1))
    js = DRIVER_CJS.replace('__CFG_JSON__', json.dumps(cfg))
    chk('driver template substitutes the config token', '__CFG_JSON__' not in js and '"cadence": 700' in js)
    chk('driver template is plain CommonJS (require, no import)', js.startswith("'use strict';") and 'require(CFG.puppeteer)' in js)

    # tier ladder only ever gets cheaper
    ts = tiers(960, 8)
    chk('tiers() start at the requested width/fps', ts[0] == (960, 8, 256))
    chk('tiers() never upscale past the request', all(t[0] <= 960 and t[1] <= 8 for t in ts))
    chk('tiers() are unique and end cheaper', len(ts) == len(set(ts)) and ts[-1][0] < 960 and ts[-1][1] <= 8)

    # scrub handling
    chk("resolve_scrub('') turns redaction off", resolve_scrub('') == [])
    chk('resolve_scrub parses an explicit list', resolve_scrub('A B,C') == ['A B', 'C'])
    chk('make_preview.py never hard-codes an account handle',
        ('Royal' + 'Spartan') not in open(os.path.abspath(__file__), encoding='utf-8').read())

    try:
        os.remove(tmp)
    except OSError:
        pass
    say('selftest: ' + ('PASS' if ok else 'FAIL'))
    return 0 if ok else 1


# --------------------------------------------------------------------------------------- #
# main                                                                                      #
# --------------------------------------------------------------------------------------- #
def main(argv=None):
    ap = argparse.ArgumentParser(description='Capture the README preview GIF + page screenshots '
                                             'from the running local dashboard.',
                                 formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    ap.add_argument('--url', default=DEFAULT_URL, help='dashboard base URL (must already be running)')
    ap.add_argument('--node', default=None, help='path to node.exe')
    ap.add_argument('--chrome', default=None, help='path to chrome.exe')
    ap.add_argument('--puppeteer-core', default=None, help='path to a puppeteer-core install')
    ap.add_argument('--cadence', type=int, default=700, help='milliseconds between tour frames')
    ap.add_argument('--width', type=int, default=960, help='output animation width in px')
    ap.add_argument('--fps', type=int, default=8, help='output animation frame rate')
    ap.add_argument('--max-mb', type=float, default=4.0, help='size budget for assets/preview.gif')
    ap.add_argument('--theme', type=int, default=14, help='palette index used for the mid-tour switch (14 = Frost Light)')
    ap.add_argument('--scrub', default=None,
                    help='comma-separated names to blur in every capture; default reads '
                         'WFM_PREVIEW_SCRUB + tools/preview_frames/redact.txt (empty = no redaction)')
    ap.add_argument('--skip-posters', action='store_true', help='do not write assets/shot_*.png')
    ap.add_argument('--from-frames', action='store_true',
                    help='skip the browser capture and assemble the frames already in tools/preview_frames/')
    ap.add_argument('--only-frames', action='store_true', help='capture frames, do not assemble')
    ap.add_argument('--assemble', choices=['auto', 'ffmpeg', 'pillow', 'none'], default='auto',
                    help='which tool assembles the animation')
    ap.add_argument('--out', default=None, help='output animation path (default assets/preview.gif)')
    ap.add_argument('--keep-frames', action='store_true', default=True,
                    help='keep tools/preview_frames/ after a successful run (default: keep)')
    ap.add_argument('--view', type=str, default=None, help=argparse.SUPPRESS)
    ap.add_argument('--selftest', action='store_true', help='run offline checks and exit')
    args = ap.parse_args(argv)

    if args.selftest:
        return selftest()

    scrub = resolve_scrub(args.scrub)

    # -- preflight ----------------------------------------------------------------------
    if args.from_frames:
        node = chrome = pptr = None
        frames = sorted(glob.glob(os.path.join(FRAMES, 'frame_*.png')))
        if not frames:
            die('--from-frames: no frames in %s - run a capture first' % FRAMES)
    else:
        node = which_node(args.node)
        chrome = which_chrome(args.chrome)
        pptr = which_puppeteer(args.puppeteer_core)
        missing = []
        if not node:
            missing.append('node  (install Node.js, or pass --node / set WFM_NODE)')
        if not chrome:
            missing.append('Chrome/Edge  (pass --chrome / set WFM_CHROME)')
        if not pptr:
            missing.append('puppeteer-core  (npm i puppeteer-core in a scratch dir and pass '
                           '--puppeteer-core, or set WFM_PUPPETEER_CORE; default searched: '
                           + PUPPETEER_CANDIDATES[1] + ')')
        if missing:
            die('missing prerequisite(s):\n  - ' + '\n  - '.join(missing))
        if not server_ok(args.url):
            die('no dashboard at %s - start it first (`python server.py` or start.bat) and leave it running.' % args.url)

    os.makedirs(FRAMES, exist_ok=True)
    os.makedirs(ASSETS, exist_ok=True)
    if not args.from_frames:
        for old in glob.glob(os.path.join(FRAMES, 'frame_*.png')):
            os.remove(old)
    for old in glob.glob(os.path.join(FRAMES, 'preview_build.gif')) + glob.glob(os.path.join(FRAMES, 'palette_build.png')):
        try:
            os.remove(old)
        except OSError:
            pass

    say('WFM Trader preview builder')
    say('  url        : %s' % args.url)
    if not args.from_frames:
        say('  node       : %s' % node)
        say('  chrome     : %s' % chrome)
        say('  puppeteer  : %s' % pptr)
    else:
        say('  mode       : --from-frames (assembling %d captured frames)' % len(frames))
    say('  frames     : %s' % FRAMES)
    say('  cadence    : %d ms' % args.cadence)
    say('  redaction  : %s' % (', '.join(scrub) if scrub else
                               '(off - pass --scrub "Handle,Name" or write tools/preview_frames/redact.txt)'))

    if args.from_frames:
        first = png_size(frames[0]) or (0, 0)
        say('\nusing the %d existing frames in %s (%dx%d)' % (len(frames), FRAMES, first[0], first[1]))
    else:
        cfg = dict(
            url=args.url.rstrip('/'), cadence=args.cadence,
            w=1440, h=900, poster_w=1440, poster_h=1000,
            theme=args.theme, scrub=scrub,
            frames=FRAMES, assets=ASSETS, puppeteer=pptr, chrome=chrome,
            posters=(not args.skip_posters),
            holds=dict(home=7000, trader=5200, guardrails=6200, theme=3800,
                       market=4200, market_scroll=4200, collection=7000, cards=7000),
        )
        driver = build_driver(cfg, os.path.join(FRAMES, 'driver.cjs'))

        t0 = time.time()
        say('\ncapturing (tour: home -> trader -> settings/guardrails -> theme -> market -> collection -> cards) ...')
        try:
            rc, out, err = run([node, driver], timeout=900)
        except subprocess.TimeoutExpired:
            die('the capture run timed out after 900s', 1)
        summary = None
        for line in (out or '').splitlines():
            if line.startswith('PREVIEW_JSON '):
                try:
                    summary = json.loads(line[len('PREVIEW_JSON '):])
                except ValueError:
                    summary = None
        if summary is None:
            say((err or out or '(no output)')[-2000:])
            die('the capture run produced no summary - see the output above', 1)
        frames = sorted(glob.glob(os.path.join(FRAMES, 'frame_*.png')))
        if not summary.get('ok') or not frames:
            say(json.dumps(summary, indent=1)[:1500])
            die('capture failed', 1)

        first = png_size(frames[0]) or (0, 0)
        say('  captured %d frames in %.1fs (%dx%d)' % (len(frames), time.time() - t0, first[0], first[1]))
        if summary.get('diag'):
            say('  diagnostics: %s' % json.dumps(summary['diag'])[:400])
        if summary.get('pageErrors'):
            say('  page errors: %s' % json.dumps(summary['pageErrors'])[:400])
        for p in summary.get('posters') or []:
            full = os.path.join(ASSETS, p)
            say('  poster  %-22s %7.1f KB  %s' % (p, os.path.getsize(full) / 1024.0, png_size(full)))

        if args.only_frames or args.assemble == 'none':
            say('\nframes kept in %s (assembly skipped)' % FRAMES)
            return 0

    # -- assembly -----------------------------------------------------------------------
    out_path = args.out or os.path.join(ASSETS, 'preview.gif')
    ffmpeg = have_ffmpeg() if args.assemble in ('auto', 'ffmpeg') else None
    result = None
    if args.assemble == 'ffmpeg' and not ffmpeg:
        die('--assemble ffmpeg was requested but ffmpeg is not on PATH')
    if ffmpeg:
        say('\nassembling with ffmpeg (%s) ...' % ffmpeg)
        result = assemble_gif_ffmpeg(ffmpeg, frames, out_path, args.max_mb, first, args.fps, args.width)
        if result.get('path') is None:
            say('  ' + str(result.get('error')))
            result = None
    if result is None and (args.assemble in ('auto', 'pillow')) and have_pillow():
        say('assembling with Pillow ...')
        pillow_out = out_path if args.assemble == 'pillow' else os.path.splitext(out_path)[0] + '.webp'
        result = assemble_pillow(frames, pillow_out, args.width, args.fps, args.max_mb)
    if result is None and args.assemble == 'pillow' and not have_pillow():
        die('--assemble pillow was requested but Pillow is not importable (`pip install pillow`)')

    if result is None:
        note = write_build_note(args.fps, args.width, args.max_mb)
        say('\nno ffmpeg and no Pillow available - frames kept in %s' % FRAMES)
        say('wrote %s with the exact commands to build the GIF later.' % note)
        say('add this line to README.md once the GIF exists:')
        say('  ![Dashboard preview](assets/preview.gif)')
        return 0

    say('')
    if result.get('tool') == 'ffmpeg':
        say('preview   : %s' % result['path'])
        say('            %.2f MB, %d frames, %d px wide @ %d fps (%d colours), %.1fs loop'
            % (result['size'] / 1048576.0, result['frames'], result['width'], result['fps'],
               result['colors'], result['duration']))
        say('            %s' % result['note'])
        if result.get('publish') != 'replaced':
            say('            note: the destination was held open by another process, so the file '
                'was overwritten in place (%s)' % result.get('publish'))
    else:
        for ext, (path, size) in sorted(result['written'].items()):
            say('preview   : %s  (%.2f MB)' % (path, size / 1048576.0))
        say('            %d frames, %d px wide @ %d fps, %.1fs loop'
            % (result['frames'], result['width'], result['fps'], result['duration']))
    say('\ndone. README embed: ![Dashboard preview](%s)'
        % os.path.relpath(result['path'], ROOT).replace('\\', '/'))
    return 0


if __name__ == '__main__':
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(130)
